file_format: "1"
id: perosweep1
name: Sweep/perosweep1
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - perosweep1_left
  - perosweep1_right
